# Generated by Django 5.0.7 on 2024-07-16 13:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Idata',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField()),
                ('level', models.PositiveIntegerField()),
                ('path', models.TextField()),
                ('description', models.TextField(blank=True)),
            ],
        ),
    ]
