# Generated by Django 5.0.7 on 2024-07-17 09:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0002_idata_usuario'),
    ]

    operations = [
        migrations.AddField(
            model_name='idata',
            name='isDirectory',
            field=models.BooleanField(default=False),
        ),
    ]
