# Generated by Django 5.0.7 on 2024-07-17 11:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0003_idata_isdirectory'),
    ]

    operations = [
        migrations.AddField(
            model_name='idata',
            name='pathRoot',
            field=models.TextField(default=''),
        ),
    ]
