# Generated by Django 5.0.7 on 2024-07-18 09:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0004_idata_pathroot'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='idata',
            options={'ordering': ['-isDirectory']},
        ),
        migrations.AddField(
            model_name='idata',
            name='Exclude',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='idata',
            name='description',
            field=models.CharField(max_length=1000),
        ),
    ]
