# Generated by Django 5.0.7 on 2024-07-18 11:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0005_alter_idata_options_idata_exclude_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='idata',
            name='SavePath',
            field=models.TextField(default=''),
        ),
    ]
