# Generated by Django 5.0.7 on 2024-07-22 13:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0008_idata_modification_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='idata',
            name='created_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
