# Generated by Django 5.0.7 on 2024-07-23 09:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0009_idata_created_at'),
    ]

    operations = [
        migrations.RenameField(
            model_name='idata',
            old_name='created_at',
            new_name='last_update',
        ),
    ]
