# Generated by Django 5.0.7 on 2024-07-23 11:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0010_rename_created_at_idata_last_update'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='idata',
            name='modification_date',
        ),
    ]
