# Generated by Django 5.0.7 on 2024-07-23 13:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0011_remove_idata_modification_date'),
    ]

    operations = [
        migrations.RenameField(
            model_name='idata',
            old_name='Exclude',
            new_name='needUpdate',
        ),
    ]
