# Generated by Django 5.0.7 on 2024-08-23 08:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0013_savedjsons'),
    ]

    operations = [
        migrations.RenameField(
            model_name='idata',
            old_name='description',
            new_name='AssetDescription',
        ),
        migrations.RenameField(
            model_name='idata',
            old_name='name',
            new_name='AssetName',
        ),
        migrations.RenameField(
            model_name='idata',
            old_name='last_update',
            new_name='updated_at',
        ),
        migrations.RemoveField(
            model_name='idata',
            name='usuario',
        ),
        migrations.AddField(
            model_name='idata',
            name='CurrentVersion',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
